//<STRING> => "string" ;

//<file> => <hdr> & <row> ;
<row> => <row> & "jooj";
<row> => "" & <a>;
//<hdr> => <row>;
//<row> => <field> & <morefield> & "\r" & "\n" ;

//<morefield> => "," & <field> & <morefield>;
//<morefield> => "";


//<field> = > <text> | <string> | "";

//<TEXT>  => "text";
